version: "2"
services:
  node_web:
    container_name: node_web
    build: ./
    image: "node_web:latest"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports: 
        - "8888:8888"
    depends_on:
      - node_mongo
    command: "npm run dev"

  node_mongo:
    container_name: node_mongo
    image: "mongo"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - "./db:/data/db"
    expose:
      - "27017"
    ports:
      - "27017:27017"
