version: "2"
services:
  node_web:
    container_name: node_web
    build: ./
    image: "node_web:latest"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports: 
        - "8888:8888"
    # command: "node app.js"
    command: "npm run dev"

  # mysqld:
  #   container_name: node_mysql
  #   image: "mysql:5.7"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 12345678
  #   volumes:
  #     - "./db:/var/lib/mysql"
  #     - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  #   ports:
  #     - "3306:3306"
  